version: "3.8"

services:
  # PHP
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - ./../:/var/www/

  # Nginx
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  # Postgres
  database:
    container_name: postgres
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Trust all connections
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data: